export const dummyData = [
	{
		id: "demo1",
		title: "Demo 1 - business",
		category: ["business"],
		available: ["gutenberg", "elementor"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["qubely", "elementor"],
	},
	{
		id: "demo2",
		title: "Demo 2 - business, blog",
		category: ["business", "blog"],
		available: ["gutenberg"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["qubely"],
	},
	{
		id: "demo3",
		title: "Demo 3 - agency",
		category: ["agency"],
		available: ["gutenberg", "elementor"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["qubely", "elementor"],
	},
	{
		id: "demo4",
		title: "Demo 4 - portfolio",
		category: ["portfolio"],
		available: ["gutenberg"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["qubely"],
	},
	{
		id: "demo5",
		title: "Demo 5 - blog",
		category: ["blog"],
		available: ["gutenberg", "elementor"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["qubely", "elementor"],
	},
	{
		id: "demo6",
		title: "Demo 5 - portfolio, agency",
		category: ["agency", "portfolio"],
		available: ["elementor"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["elementor"],
	},
	{
		id: "demo7",
		title: "Demo 7 - education, agency",
		category: ["agency", "education"],
		available: ["elementor"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["elementor"],
	},
];
