export const dummyData = [
	{
		id: "demo1",
		title: "Demo 1",
		category: ["business"],
		available: ["gutenberg", "elementor"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["qubely", "elementor"],
	},
	{
		id: "demo2",
		title: "Demo 2",
		category: ["business", "blog"],
		available: ["gutenberg"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["qubely"],
	},
	{
		id: "demo3",
		title: "Demo 3",
		category: ["agency"],
		available: ["gutenberg", "elementor"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["qubely", "elementor"],
	},
	{
		id: "demo4",
		title: "Demo 4",
		category: ["portfolio"],
		available: ["gutenberg"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["qubely"],
	},
	{
		id: "demo5",
		title: "Demo 5",
		category: ["blog"],
		available: ["gutenberg", "elementor"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["qubely", "elementor"],
	},
	{
		id: "demo6",
		title: "Demo 5",
		category: ["agency", "portfolio"],
		available: ["elementor"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["elementor"],
	},
	{
		id: "demo7",
		title: "Demo 7",
		category: ["agency", "education"],
		available: ["elementor"],
		imgUrl: "http://placehold.it/350x250",
		plugins: ["elementor"],
	},
];
